# https://docs.ansible.com/ansible/latest/scenario_guides/guide_gce.html
- name: Manages instances group
  hosts: localhost
  gather_facts: yes
  vars:
      gcp_project: livraison-express-213321
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ./files/livraison-express-213321-7058bc3205c6.json
      zone: europe-west1-b
      region: europe-west1
      env: staging
      discreminator: instance-1
      app_name: livraison-express

  tasks:
  - name: create a network
    gcp_compute_network:
      name: "{{ app_name }}-network"
      auto_create_subnetworks: 'true'
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: network

  # - name: get info on default network
  #   gcp_compute_network_info:
  #     filters:
  #     - name = "default"
  #     project: "{{ gcp_project }}"
  #     auth_kind: "{{ gcp_cred_kind }}"
  #     service_account_file: "{{ gcp_cred_file }}"
  #   register: network