---

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  become: true

- name: Copy custom fail2ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart fail2ban

- name: Ensure fail2ban starts on a fresh reboot
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: true
