---

- name: get info on a disk
  gcp_compute_disk_info:
    filters:
      - name = shared-disk-1
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    register: shared_disk
  delegate_to: localhost

- name: Debug disk
  debug:
    var: shared_disk
    verbosity: 0
#        msg: "i am good, {{ address.address }}"

- name: Mount shared disk
  mount:
    path: /mnt/shared
    src: /dev/sr0
    fstype: ext4
    opts: discard,defaults
    state: present
